### ISSUE TITLE
option<const T&> and sentinels broken

### ISSUE THREAD

**Issue by BjornSAIM** [NUCLEAR-BOMB/option#2]
Hi,

I've been trying to replace my current implementation (Optional26 with local sentinel based overloads) with this one, but I've run into several issues that make it unusable:
The range support doesn't seem to be properly implementation for (const) references. Trying to use it simply doesn't compile. This seems to be related to these parts:

`using value_type = std::remove_cv_t<T>;
using reference = T&; 
using difference_type = std::ptrdiff_t;
using pointer = T*;`

Which I believe should look like this:

`using value_type = std::remove_reference_t<T>;
using reference = value_type&;
using difference_type = std::ptrdiff_t;
using pointer = value_type*;`

As it needs to respect constness (because the const_iterator relies on T being specified as a const type). And when T is a reference T* ends up being a &* which is not correct.

The second problem I ran into is when I have a type that has a single field of type uint64_t, for which I specific the max-value to be the sentinel value using an opt::option_traits overload. And I then construct the option from the sentinel value, an assert is fired because the constructor expects has_value to be true, which is not a correct assertions for this specific case.

**Comment by NUCLEAR-BOMB** [comment]
Hey!
Your first issue should be fixed in b58df5da69944c5ffbbb3e1a9f22120394589529.

For the second one, I think your implementation of `opt::option_traits` is incorrect. From your words, it should be something like this:
```cpp
template<>
struct opt::option_traits<your_type> {
    static constexpr std::uintmax_t max_level = 1;
    static constexpr std::uintmax_t get_level(const your_type* value) noexcept {
        return value->that_field - std::numeric_limits<uint64_t>::max();
    }
    static constexpr void set_level(your_type* value, [[maybe_unused]] std::uintmax_t level) noexcept {
        value->that_field = std::numeric_limits<uint64_t>::max();
    }
};
```

For more information you can always check [`opt::option_traits` documentation](https://nuclear-bomb.github.io/option/#/reference?id=optoption_traits) and [custom `opt::option_traits` guide](https://nuclear-bomb.github.io/option/#/custom_traits_guide).

If that still doesn't help, you can disable internal asserts by defining preprocessor macro `OPTION_VERIFY` (e.g. `#define OPTION_VERIFY(expr, msg)`) (for more, see [`OPTION_VERIFY` documentation](https://nuclear-bomb.github.io/option/#/macros?id=option_verify)) and check if your program works fine without safeguards.

If I have solved your problems, I can release v1.3.1, which will include fix for your first problem. Thanks for submitting!

**Comment by BjornSAIM** [comment]
I believe your fix will still fail on const refs.

My option_traits is equivalent to yours. I already def-ed out the assert and my software behaves correctly since.
The verify asserts engaged() when constructing from value. To me it seems obvious this won't hold up when the value in question is the one I use to represent non-engagement.

**Comment by NUCLEAR-BOMB** [comment]
I think what are you trying to do is something like this:
```cpp
my_val.field != std::numeric_limits<std::uint64_t>::max() ? opt::option{my_val} : opt::none;
```
The `opt::option` after construction should always be an engaged one (except for default and from `opt::none_t` constructors), so you cannot initialize an `opt::option` in an empty state using the sentinel value.

Perhaps there should be a function/constructor to account for these cases? (couldn't think of a name, though).

About your first issue, I don't see how that could happen. Could you describe it more?

**Comment by BjornSAIM** [comment]
Hi, didn't have access to my codebase before, so couldn't verify.

> I think what are you trying to do is something like this:
> 
> ```c++
> my_val.field != std::numeric_limits<std::uint64_t>::max() ? opt::option{my_val} : opt::none;
> ```
> 
> The `opt::option` after construction should always be an engaged one (except for default and from `opt::none_t` constructors), so you cannot initialize an `opt::option` in an empty state using the sentinel value.
> 
> Perhaps there should be a function/constructor to account for these cases? (couldn't think of a name, though).

That's basically it, yes. Maybe I should elaborate a bit on the context. Originally I had built an api that hands out "Entities", which are represented by a uint64_t. I wrapped this in an Entity type that supports a public static const field nullValue (and bool operator). I wasn't happy with this, because it has sort of the same semantic ambiguity as pointers do (do I need to check it or not). So I made an optional overload for Entities that only stores an Entity and uses nullValue (and the bool operator) for dealing with engagement.
Because passing in the empty value is a legitimate way of empty initialisation in my implementation. I could actually just use the optional as a drop in replacement at the boundaries of my API and it just worked.

Now from what I understand this is undesirable for your implementation. I guess when you have an actual multi-level type, doing what I'm doing can lead to undesired behaviour.

I will just keep the OPTION_VERIFY overridden for now. And possibly correct the implementation if I decide to stick with this implementation (I like it, but I'm a little concerned about potential UB and platform dependence).

> About your first issue, I don't see how that could happen. Could you describe it more?

I took in your dev branch just now and the const refs seem to compile fine now.

So I have no further issues.

**Comment by NUCLEAR-BOMB** [comment]
@BjornSAIM Glad I could help you.

> I will just keep the OPTION_VERIFY overridden for now

To be honest, I don't really like this approach. The `OPTION_VERIFY` is created to check for erroneous behaviour within `opt::option`.

I'm thinking to add something like `opt::checked_make_option`, which will look something like this:
```cpp
template<class T>
constexpr opt::option<T> checked_make_option(const T& arg) {
    if (opt::option_traits<T>::get_level(std::addressof(arg)) != 0) {
        return opt::option<T>{arg};
    } else {
        return opt::none;
    }
}
```
Or, maybe a `opt::option` constructor that specifically will not do any `OPTION_VERIFY` inside it.
E.g. something like this:
```cpp
opt::option<some_type>{opt::unchecked, ULLONG_MAX};
```
Also maybe a preprocessor macro `OPTION_UNCHECKED_INITIALIZATION` which would disable `OPTION_VERIFY` inside `opt::option`'s constructors, `.reset()` and `.emplace()`.

> And possibly correct the implementation if I decide to stick with this implementation (I like it, but I'm a little concerned about potential UB and platform dependence).

Although I will not deny that the library does have undefined behavior, it **only** happens when the underlying type is not trivially copyable + I would be very surprised if you can give an example when that UB would produce erroneous behavior.
Yes, in some built-in `opt::option_traits` implementations there is platform dependence stuff (e.g. in member pointers, `std::vector`, `std::string`, etc.), but if you have any problems with them you can [override and disable them](https://nuclear-bomb.github.io/option/#/custom_traits_guide?id=disabling-specializations). There is also a preprocessor macro [`OPTION_USE_BUILTIN_TRAITS`](https://nuclear-bomb.github.io/option/#/macros?id=option_use_builtin_traits) that disables all default `opt::option_traits` (it is currenly not working, will be fixing it).

> That's basically it, yes. Maybe I should elaborate a bit on the context. Originally I had built an api that hands out "Entities", which are represented by a uint64_t. I wrapped this in an Entity type that supports a public static const field nullValue (and bool operator). I wasn't happy with this, because it has sort of the same semantic ambiguity as pointers do (do I need to check it or not). So I made an optional overload for Entities that only stores an Entity and uses nullValue (and the bool operator) for dealing with engagement.

I guess something like Rust's [`NonZeroU64`](https://doc.rust-lang.org/std/num/type.NonZeroU64.html) would be perfectly fit into your requirements but I don't like it being a seperate type (metafunctions like `std::is_integral` will not work on it). I'm thinking about "custom option traits", a second template parameter in `opt::option` which would redefine the default `opt::option_traits` so you can do something like this: `opt::option<uint64_t, opt::nonmax>{1}`. But again, what will happen if you construct it with a sentinel value? Triggering `OPTION_VERIFY`? I don't really like it either.

Maybe something like `opt::make_nonmax(std::uint64_t)`. A function that will return `opt::option<uint64_t, opt::nonmax>` if the passed argument is a valid one. But yeah, custom option traits are not currenly implemented.

By the way, I'm planning to add `opt::expected` (like `std::expected` but better), custom option traits, package library in compiler explorer, vcpkg and conan, reimplement `boost.pfr` to support extended reflection (and maybe faster compile times?) and more.

What do you think?

**Comment by BjornSAIM** [comment]
opt::expected is something I would use, to have parity with the optional counterpart.

With regards the rest. I think it might be interesting to have a simpler variation of opt::option_traits for which you only need to supply a "T empty_value". You could then also have an optional parameter alongside it like: "constexpr static bool allow_empty_value_construction" or something. That way you can avoid the ambiguity that arises when using the level api, and it also provides a simpler alternative to users that might find the level api daunting (it's quite good, but it did take me a couple of moments to realise why it needed to be done that way).

My Entity representation is actually split in 2 parts. a 48 bit id and a 16 bit version. So the last 16 bits are actually enough to represent an empty value. So I'm more likely to eventually implement a multilevel implementation than and update the way I'm constructing the optional than sticking the above suggestion.

**Comment by NUCLEAR-BOMB** [comment]
> With regards the rest. I think it might be interesting to have a simpler variation of opt::option_traits for which you only need to supply a "T empty_value".

Probably CRTP could fit here very well. For example,
```cpp
template<>
struct opt::option_traits<my_very_cool_type> : opt::use_empty_value<my_very_cool_type> {
    static constexpr my_very_cool_type empty_value{1, 2, 3};
};
```
This would automatically generate `get_level` and `set_level` functions using the `empty_value` as a sentinel.

>  You could then also have an optional parameter alongside it like: "constexpr static bool allow_empty_value_construction" or something

I don't think thats a good idea to make it implicit. This could go very badly if a value with `allow_empty_value_construction` gets passed into some template function which would expected that the `opt::option` is constructed using that type will always contain a value.

To be honest, I don't understand why would you ever want to construct a option using a sentinel value. The purpose of option is to replace magic values with a convenient interface to them.
